"""
Seed script to populate MongoDB with Goa destination data.
Run: python seed.py
"""
import asyncio
from motor.motor_asyncio import AsyncIOMotorClient
from config import settings

DESTINATIONS = [
    {
        "name": "Baga Beach",
        "description": "One of the most popular beaches in North Goa, known for its vibrant nightlife, water sports, and lively beach shacks. The perfect blend of relaxation and excitement with golden sands stretching along the Arabian Sea.",
        "image_url": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800",
        "location": "North Goa",
        "category": "beach",
        "rating": 4.5,
        "tags": ["nightlife", "water sports", "popular", "shacks"],
        "lat": 15.5553,
        "lng": 73.7517,
        "highlights": ["Jet skiing", "Parasailing", "Tito's Lane nightlife", "Beach shacks"],
        "best_time": "November to February",
    },
    {
        "name": "Palolem Beach",
        "description": "A stunning crescent-shaped beach in South Goa, famous for its calm waters, colorful beach huts, and laid-back bohemian vibe. Often called one of the most beautiful beaches in India.",
        "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
        "location": "South Goa",
        "category": "beach",
        "rating": 4.8,
        "tags": ["peaceful", "scenic", "kayaking", "dolphin watching"],
        "lat": 15.0100,
        "lng": 74.0230,
        "highlights": ["Silent noise parties", "Kayaking to Butterfly Island", "Dolphin spotting", "Colorful beach huts"],
        "best_time": "October to March",
    },
    {
        "name": "Anjuna Beach",
        "description": "The birthplace of Goa's famous trance music scene and home to the iconic Wednesday Flea Market. A bohemian paradise with dramatic rocky outcrops and stunning sunset views.",
        "image_url": "https://images.unsplash.com/photo-1506953823976-52e1fdc0149a?w=800",
        "location": "North Goa",
        "category": "beach",
        "rating": 4.3,
        "tags": ["bohemian", "flea market", "trance", "sunset"],
        "lat": 15.5735,
        "lng": 73.7412,
        "highlights": ["Wednesday Flea Market", "Curlies Beach Shack", "Trance parties", "Rocky cliff views"],
        "best_time": "November to February",
    },
    {
        "name": "Agonda Beach",
        "description": "A serene, unspoiled beach in South Goa, perfect for those seeking tranquility. With minimal commercialization and stunning natural beauty, it's an ideal spot for yoga and meditation.",
        "image_url": "https://images.unsplash.com/photo-1473116763249-2faaef81ccda?w=800",
        "location": "South Goa",
        "category": "beach",
        "rating": 4.7,
        "tags": ["serene", "yoga", "nature", "turtle nesting"],
        "lat": 15.0445,
        "lng": 73.9880,
        "highlights": ["Olive Ridley turtle nesting", "Yoga retreats", "Pristine sands", "Stargazing"],
        "best_time": "October to March",
    },
    {
        "name": "Calangute Beach",
        "description": "Known as the 'Queen of Beaches,' Calangute is Goa's largest and most famous beach. A bustling hub of activity with restaurants, shops, and water sports lining the shore.",
        "image_url": "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800",
        "location": "North Goa",
        "category": "beach",
        "rating": 4.1,
        "tags": ["popular", "shopping", "water sports", "family"],
        "lat": 15.5438,
        "lng": 73.7553,
        "highlights": ["Water sports hub", "Shopping arcade", "Kerkar Art Complex", "Goan cuisine stalls"],
        "best_time": "November to February",
    },
    {
        "name": "Fort Aguada",
        "description": "A well-preserved 17th-century Portuguese fort overlooking the Arabian Sea. The fort includes a lighthouse and offers panoramic views of the coastline, blending history with natural beauty.",
        "image_url": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800",
        "location": "North Goa",
        "category": "fort",
        "rating": 4.4,
        "tags": ["heritage", "lighthouse", "views", "history"],
        "lat": 15.4924,
        "lng": 73.7736,
        "highlights": ["Historic lighthouse", "Panoramic ocean views", "Portuguese architecture", "Sinquerim Beach nearby"],
        "best_time": "Year-round, best Nov-Feb",
    },
    {
        "name": "Dudhsagar Falls",
        "description": "One of India's tallest waterfalls at 310 meters, cascading dramatically through lush tropical forest. The name means 'Sea of Milk' due to its white, foamy appearance.",
        "image_url": "https://images.unsplash.com/photo-1432405972618-c6b0cfba8b15?w=800",
        "location": "East Goa (Sanguem)",
        "category": "waterfall",
        "rating": 4.6,
        "tags": ["waterfall", "trekking", "nature", "adventure"],
        "lat": 15.3144,
        "lng": 74.3143,
        "highlights": ["4-tier waterfall", "Jeep safari through forest", "Natural swimming pool", "Train bridge views"],
        "best_time": "October to March (post-monsoon)",
    },
    {
        "name": "Vagator Beach",
        "description": "A scenic beach nestled below dramatic red cliffs, known for its stunning sunset views over Chapora Fort. A quieter alternative to neighboring Anjuna with a cool, artistic vibe.",
        "image_url": "https://images.unsplash.com/photo-1468413253725-0d5181091126?w=800",
        "location": "North Goa",
        "category": "beach",
        "rating": 4.5,
        "tags": ["sunset", "cliffs", "peaceful", "artistic"],
        "lat": 15.5970,
        "lng": 73.7350,
        "highlights": ["Chapora Fort sunset", "Shiva face rock carving", "Hilltop bars", "Red cliff views"],
        "best_time": "November to February",
    },
    {
        "name": "Basilica of Bom Jesus",
        "description": "A UNESCO World Heritage Site and one of the oldest churches in India, housing the mortal remains of St. Francis Xavier. A masterpiece of Baroque architecture dating to 1605.",
        "image_url": "https://images.unsplash.com/photo-1564399579883-451a5d44ec08?w=800",
        "location": "Old Goa",
        "category": "temple",
        "rating": 4.6,
        "tags": ["UNESCO", "heritage", "church", "architecture"],
        "lat": 15.5009,
        "lng": 73.9116,
        "highlights": ["St. Francis Xavier's tomb", "Baroque architecture", "UNESCO World Heritage", "Art gallery"],
        "best_time": "Year-round",
    },
    {
        "name": "Arambol Beach",
        "description": "A bohemian haven in the far north of Goa, known for its drum circles at sunset, hippie culture, and a hidden sweet-water lake behind the beach. Retains old Goa's free-spirited charm.",
        "image_url": "https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=800",
        "location": "North Goa",
        "category": "beach",
        "rating": 4.4,
        "tags": ["bohemian", "drum circles", "hippie", "sweet water lake"],
        "lat": 15.6866,
        "lng": 73.7046,
        "highlights": ["Sunset drum circles", "Paragliding", "Sweet water lake", "Yoga shalas"],
        "best_time": "November to March",
    },
    {
        "name": "Spice Plantations",
        "description": "Experience the aromatic world of Goa's spice plantations in Ponda. Guided tours through lush gardens of cardamom, pepper, vanilla, and cinnamon, ending with a traditional Goan lunch.",
        "image_url": "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800",
        "location": "Ponda, Central Goa",
        "category": "nature",
        "rating": 4.3,
        "tags": ["spices", "nature walk", "traditional", "food"],
        "lat": 15.4030,
        "lng": 74.0080,
        "highlights": ["Guided spice tours", "Traditional Goan lunch", "Elephant bathing", "Organic farming"],
        "best_time": "October to March",
    },
    {
        "name": "Candolim Beach",
        "description": "A quieter, more upscale neighbor to Calangute, Candolim offers a long stretch of golden sand with fewer crowds. Popular with couples and families seeking a more relaxed beach experience.",
        "image_url": "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
        "location": "North Goa",
        "category": "beach",
        "rating": 4.3,
        "tags": ["relaxed", "upscale", "family", "sunbathing"],
        "lat": 15.5155,
        "lng": 73.7623,
        "highlights": ["Fort Aguada walks", "Sinquerim Beach", "Upscale restaurants", "Water sports"],
        "best_time": "November to February",
    },
]

HOTELS = [
    {
        "name": "Taj Exotica Resort & Spa",
        "description": "A 5-star luxury resort set on 56 acres of landscaped gardens overlooking the Arabian Sea. Mediterranean-style architecture with world-class dining, an award-winning spa, and a championship golf course.",
        "image_url": "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
        "price_per_night": 18000,
        "price_range": "luxury",
        "location": "Benaulim, South Goa",
        "rating": 4.8,
        "amenities": ["Pool", "Spa", "Golf Course", "Beach Access", "Fine Dining", "Gym"],
        "type": "resort",
        "tags": ["luxury", "beachfront", "spa", "romantic"],
        "lat": 15.2473,
        "lng": 73.9343,
        "nearby_beach": "Benaulim Beach",
    },
    {
        "name": "Alila Diwa Goa",
        "description": "A boutique luxury hotel inspired by Goa's traditional laterite architecture, set amidst lush paddy fields. Features stunning infinity pools and contemporary design with Goan heritage touches.",
        "image_url": "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800",
        "price_per_night": 12000,
        "price_range": "luxury",
        "location": "Majorda, South Goa",
        "rating": 4.7,
        "amenities": ["Infinity Pool", "Spa", "Restaurant", "Bar", "Yoga", "Bicycle Rental"],
        "type": "hotel",
        "tags": ["boutique", "design", "paddy fields", "modern"],
        "lat": 15.2830,
        "lng": 73.9180,
        "nearby_beach": "Majorda Beach",
    },
    {
        "name": "The Leela Goa",
        "description": "Set along Mobor Beach with a stunning lagoon, this luxury resort features Portuguese-Goan architecture. Known for its 12-hole golf course, multiple pools, and world-class spa.",
        "image_url": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800",
        "price_per_night": 15000,
        "price_range": "luxury",
        "location": "Cavelossim, South Goa",
        "rating": 4.7,
        "amenities": ["Golf Course", "Pool", "Spa", "Beach", "Tennis", "Kids Club"],
        "type": "resort",
        "tags": ["luxury", "family", "golf", "lagoon"],
        "lat": 15.1757,
        "lng": 73.9450,
        "nearby_beach": "Mobor Beach",
    },
    {
        "name": "Elsewhere Beach House",
        "description": "A charming boutique beach house steps from Mandrem Beach. With just a handful of rooms, it feels like a private getaway. Beautiful garden, outdoor showers, and a dreamy boho-chic aesthetic.",
        "image_url": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800",
        "price_per_night": 5500,
        "price_range": "mid",
        "location": "Mandrem, North Goa",
        "rating": 4.6,
        "amenities": ["Garden", "Beach Access", "Breakfast", "Hammocks", "Library"],
        "type": "airbnb",
        "tags": ["boutique", "bohemian", "beachfront", "peaceful"],
        "lat": 15.6594,
        "lng": 73.7108,
        "nearby_beach": "Mandrem Beach",
    },
    {
        "name": "Casa Vagator",
        "description": "A stylish, contemporary hotel perched atop a hill with breathtaking views of Ozran Beach. Rooftop bar, artsy interiors, and a happening pool scene make it a favorite for young travelers.",
        "image_url": "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800",
        "price_per_night": 7000,
        "price_range": "mid",
        "location": "Vagator, North Goa",
        "rating": 4.5,
        "amenities": ["Pool", "Rooftop Bar", "Restaurant", "DJ Nights", "Gym"],
        "type": "hotel",
        "tags": ["trendy", "views", "nightlife", "design"],
        "lat": 15.5980,
        "lng": 73.7340,
        "nearby_beach": "Ozran Beach",
    },
    {
        "name": "Palolem Beach Huts",
        "description": "Authentic beach hut experience right on the sand at Palolem. Wake up to the sound of waves, step onto the beach, and enjoy the simple pleasures of beachside living in colorful bamboo huts.",
        "image_url": "https://images.unsplash.com/photo-1540541338287-41700c1d5280?w=800",
        "price_per_night": 2000,
        "price_range": "budget",
        "location": "Palolem, South Goa",
        "rating": 4.2,
        "amenities": ["Beach Access", "Fan", "Mosquito Net", "Common Area", "Restaurant"],
        "type": "guesthouse",
        "tags": ["budget", "beachfront", "authentic", "backpacker"],
        "lat": 15.0100,
        "lng": 74.0230,
        "nearby_beach": "Palolem Beach",
    },
    {
        "name": "Montego Bay Beach Village",
        "description": "A trendy mid-range resort in Morjim featuring stylish cabanas and a beautiful pool area. Known for its vibrant social scene, sunset views, and direct beach access.",
        "image_url": "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800",
        "price_per_night": 4500,
        "price_range": "mid",
        "location": "Morjim, North Goa",
        "rating": 4.4,
        "amenities": ["Pool", "Beach Access", "Restaurant", "Bar", "Yoga"],
        "type": "resort",
        "tags": ["trendy", "social", "beachfront", "yoga"],
        "lat": 15.6309,
        "lng": 73.7280,
        "nearby_beach": "Morjim Beach",
    },
    {
        "name": "Zostel Goa",
        "description": "India's most popular hostel chain, the Goa outpost offers vibrant dorms and private rooms near Anjuna. Perfect for solo travelers and backpackers looking to meet fellow adventurers.",
        "image_url": "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800",
        "price_per_night": 800,
        "price_range": "budget",
        "location": "Anjuna, North Goa",
        "rating": 4.1,
        "amenities": ["Common Area", "Kitchen", "WiFi", "Tours", "Bike Rental"],
        "type": "guesthouse",
        "tags": ["hostel", "backpacker", "social", "budget"],
        "lat": 15.5735,
        "lng": 73.7412,
        "nearby_beach": "Anjuna Beach",
    },
    {
        "name": "Ahilya by the Sea",
        "description": "An elegant boutique property on a cliff overlooking the ocean near Candolim. Inspired by the royal heritage of Maheshwar, featuring antique furnishings and personalized service.",
        "image_url": "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800",
        "price_per_night": 9500,
        "price_range": "luxury",
        "location": "Candolim, North Goa",
        "rating": 4.6,
        "amenities": ["Pool", "Ocean View", "Heritage Decor", "Personal Butler", "Garden"],
        "type": "hotel",
        "tags": ["heritage", "boutique", "ocean view", "exclusive"],
        "lat": 15.5155,
        "lng": 73.7623,
        "nearby_beach": "Candolim Beach",
    },
    {
        "name": "Treehouse Neptune Villa",
        "description": "A unique Airbnb treehouse experience nestled in the palms near Ashwem Beach. Elevated wooden villa with open-air living, surrounded by nature yet close to restaurants and beach.",
        "image_url": "https://images.unsplash.com/photo-1585543805890-6051f7829f98?w=800",
        "price_per_night": 3500,
        "price_range": "mid",
        "location": "Ashwem, North Goa",
        "rating": 4.5,
        "amenities": ["Treehouse", "Garden", "Beach Nearby", "Breakfast", "Hammock"],
        "type": "airbnb",
        "tags": ["unique", "nature", "instagram", "romantic"],
        "lat": 15.6425,
        "lng": 73.7187,
        "nearby_beach": "Ashwem Beach",
    },
]

RESTAURANTS = [
    {
        "name": "Gunpowder",
        "description": "An iconic South Indian-influenced restaurant in Assagao, set in a charming heritage house with a beautiful courtyard garden. Known for creative twists on coastal Indian cuisine using local ingredients.",
        "image_url": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
        "cuisine": "South Indian/Goan Fusion",
        "price_range": "mid",
        "location": "Assagao, North Goa",
        "rating": 4.7,
        "tags": ["heritage house", "garden dining", "local favorite", "must-visit"],
        "lat": 15.5879,
        "lng": 73.7698,
        "specialties": ["Malabar Prawn Curry", "Appam with Stew", "Pulled Pork Vindaloo", "Filter Coffee"],
        "vibe": "garden",
    },
    {
        "name": "Fisherman's Wharf",
        "description": "A beloved Goan restaurant chain right on the Mandovi River, serving fresh seafood and traditional Goan cuisine. The waterfront setting with fairy lights creates a magical dining atmosphere.",
        "image_url": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800",
        "cuisine": "Goan/Seafood",
        "price_range": "mid",
        "location": "Cavelossim, South Goa",
        "rating": 4.5,
        "tags": ["waterfront", "seafood", "romantic", "family"],
        "lat": 15.1757,
        "lng": 73.9450,
        "specialties": ["Goan Fish Curry Rice", "Prawn Balchão", "Crab Xec Xec", "Bebinca"],
        "vibe": "beachside",
    },
    {
        "name": "Britto's",
        "description": "A legendary Baga Beach institution since 1965, Britto's is where Goa's beach dining scene began. Right on the sand with your toes in it, serving everything from fresh seafood to wood-fired pizzas.",
        "image_url": "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800",
        "cuisine": "Multi-cuisine/Seafood",
        "price_range": "mid",
        "location": "Baga Beach, North Goa",
        "rating": 4.3,
        "tags": ["beachside", "legendary", "sunset", "live music"],
        "lat": 15.5553,
        "lng": 73.7517,
        "specialties": ["Grilled Fish Platter", "Goan Sausage Pulao", "Calamari", "Cocktails"],
        "vibe": "beachside",
    },
    {
        "name": "Thalassa",
        "description": "A stunning Greek restaurant perched on a cliff in Vagator with jaw-dropping sunset views. Authentic Mediterranean cuisine, whitewashed decor, and a bohemian atmosphere make it unforgettable.",
        "image_url": "https://images.unsplash.com/photo-1544148103-0773bf10d330?w=800",
        "cuisine": "Greek/Mediterranean",
        "price_range": "upscale",
        "location": "Vagator, North Goa",
        "rating": 4.6,
        "tags": ["sunset views", "cliffside", "romantic", "Greek"],
        "lat": 15.5970,
        "lng": 73.7350,
        "specialties": ["Grilled Octopus", "Moussaka", "Greek Salad", "Baklava"],
        "vibe": "rooftop",
    },
    {
        "name": "Antares",
        "description": "Chef Sarah Todd's stunning restaurant and beach club in Vagator. Contemporary Australian-influenced cuisine with Goan flair, spectacular ocean views, and a vibrant pool-party-meets-fine-dining vibe.",
        "image_url": "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800",
        "cuisine": "Australian/Asian Fusion",
        "price_range": "upscale",
        "location": "Vagator, North Goa",
        "rating": 4.5,
        "tags": ["celebrity chef", "ocean view", "brunch", "instagrammable"],
        "lat": 15.5975,
        "lng": 73.7345,
        "specialties": ["Pork Belly Bao", "Tuna Tartare", "Truffle Mushroom Pizza", "Sunset Cocktails"],
        "vibe": "rooftop",
    },
    {
        "name": "Vinayak Family Restaurant",
        "description": "A no-frills local favorite in Assagao known for serving some of the best authentic Goan food at unbeatable prices. The prawn thali here is legendary among locals and in-the-know travelers.",
        "image_url": "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800",
        "cuisine": "Authentic Goan",
        "price_range": "budget",
        "location": "Assagao, North Goa",
        "rating": 4.4,
        "tags": ["local favorite", "authentic", "budget", "thali"],
        "lat": 15.5880,
        "lng": 73.7700,
        "specialties": ["Prawn Thali", "Fish Curry Rice", "Chicken Cafreal", "Sol Kadhi"],
        "vibe": "casual",
    },
    {
        "name": "La Plage",
        "description": "A sophisticated French-influenced beach restaurant in Ashwem, known for its minimalist aesthetic, organic ingredients, and perfectly curated music. A serene escape from the tourist crowds.",
        "image_url": "https://images.unsplash.com/photo-1537047902294-62a40c20a6ae?w=800",
        "cuisine": "French/Mediterranean",
        "price_range": "upscale",
        "location": "Ashwem, North Goa",
        "rating": 4.6,
        "tags": ["minimalist", "organic", "beachfront", "sophisticated"],
        "lat": 15.6425,
        "lng": 73.7187,
        "specialties": ["Fresh Oysters", "Grilled Sea Bass", "Tartare", "French Wine"],
        "vibe": "beachside",
    },
    {
        "name": "Mum's Kitchen",
        "description": "Award-winning restaurant preserving traditional Goan recipes passed down through generations. Located in Panjim, it celebrates the rich culinary heritage of Goa through authentic home-style cooking.",
        "image_url": "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800",
        "cuisine": "Traditional Goan",
        "price_range": "mid",
        "location": "Panjim, Central Goa",
        "rating": 4.5,
        "tags": ["traditional", "heritage", "family recipes", "award-winning"],
        "lat": 15.4909,
        "lng": 73.8278,
        "specialties": ["Pork Vindaloo", "Chicken Xacuti", "Shark Ambot Tik", "Dodol"],
        "vibe": "casual",
    },
    {
        "name": "Café Bodega",
        "description": "A charming heritage café inside the Sunaparanta art center in Panjim's Fontainhas quarter. Beautiful Portuguese-era architecture, artisan coffee, and light bites in a cultural setting.",
        "image_url": "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800",
        "cuisine": "Café/Continental",
        "price_range": "mid",
        "location": "Fontainhas, Panjim",
        "rating": 4.4,
        "tags": ["heritage", "art gallery", "coffee", "instagram"],
        "lat": 15.4950,
        "lng": 73.8300,
        "specialties": ["Artisan Coffee", "Croissants", "Goan Chorizo Toast", "Fresh Juices"],
        "vibe": "garden",
    },
    {
        "name": "Purple Martini",
        "description": "A lively tapas and cocktail bar in Arpora, popular for its creative cocktails, live music, and vibrant party atmosphere. A great spot for pre-nightlife drinks and socializing.",
        "image_url": "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800",
        "cuisine": "Tapas/International",
        "price_range": "mid",
        "location": "Arpora, North Goa",
        "rating": 4.2,
        "tags": ["cocktails", "live music", "nightlife", "tapas"],
        "lat": 15.5650,
        "lng": 73.7560,
        "specialties": ["Signature Cocktails", "Tapas Platter", "Nachos Tower", "Sangria"],
        "vibe": "rooftop",
    },
]


async def seed():
    client = AsyncIOMotorClient(settings.MONGO_URL)
    db = client[settings.DB_NAME]

    # Clear existing data
    await db["destinations"].delete_many({})
    await db["hotels"].delete_many({})
    await db["restaurants"].delete_many({})

    # Insert seed data
    if DESTINATIONS:
        result = await db["destinations"].insert_many(DESTINATIONS)
        print(f"✅ Inserted {len(result.inserted_ids)} destinations")

    if HOTELS:
        result = await db["hotels"].insert_many(HOTELS)
        print(f"✅ Inserted {len(result.inserted_ids)} hotels")

    if RESTAURANTS:
        result = await db["restaurants"].insert_many(RESTAURANTS)
        print(f"✅ Inserted {len(result.inserted_ids)} restaurants")

    print("🌴 Database seeded successfully!")
    client.close()


if __name__ == "__main__":
    asyncio.run(seed())
